/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-ZQFk7HQTy2tRKQoaZIsu2IHxuZUCKJH8FJTsKJzsCOjmK8yad5NKcsBchk9KyFnDmp2oZ0yyKy-kKGA3yCdCnFaCTLnIMI194ayC7xkV5sZqZtLkREIl8hfX",
  "tt": "tt-1-3A-ba32Izo-JSYj1fs1qPXU6TPaFXmXvPXUZ5jyPpB8=",
  "version": "2020-11-20"
}

export default ebconfig;